### ISSUE TITLE
main.h:441:42: error: 'CTxDestination' does not name a type

### ISSUE THREAD

**Issue by unsystemizer** [btcdrak/bitcoin#4] opened 2016-02-20 08:15 UTC
Getting this on Raspbian with bitcoin-addrindex-0.12.0 branch:

```
make[3]: Leaving directory '/blockchain/source/bitcoin-addrindex-0.12/src/secp256k1'
  CXX      libbitcoin_server_a-httpserver.o
  CXX      libbitcoin_server_a-init.o
In file included from checkpoints.cpp:9:0:
main.h:441:42: error: 'CTxDestination' does not name a type
 bool FindTransactionsByDestination(const CTxDestination &dest, std::set<CExtDiskTxPos> &setpos);
                                          ^
Makefile:3729: recipe for target 'libbitcoin_server_a-checkpoints.o' failed
make[2]: *** [libbitcoin_server_a-checkpoints.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from init.cpp:22:0:
main.h:441:42: error: 'CTxDestination' does not name a type
 bool FindTransactionsByDestination(const CTxDestination &dest, std::set<CExtDiskTxPos> &setpos);
                                          ^
Makefile:3771: recipe for target 'libbitcoin_server_a-init.o' failed
make[2]: *** [libbitcoin_server_a-init.o] Error 1
make[2]: Leaving directory '/blockchain/source/bitcoin-addrindex-0.12/src'
Makefile:6904: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/blockchain/source/bitcoin-addrindex-0.12/src'
Makefile:641: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

BItcoin Issue 2802 (2802#issuecomment-21841017) is the only similar error I was able to find on this.

**Comment by JornC** [comment] 2016-02-23 15:35
Managed to fix some of the errors:

https://github.com/JornC/bitcoin/commit/af04fbd513425d97218b820e1ffca3ad868bce0c

Still having issues in txdb.cpp with the CDB changes that are beyond our ability of solving.

Not submitting a pull because the above fix is incomplete.

Cheers. :+1:

**Comment by btcdrak** [comment] 2016-02-24 13:37
Should be fixed in a89810b

**Comment by btcdrak** [comment] 2016-02-24 16:29
@JornC @unsystemizer Please confirm.

**Comment by JornC** [comment] 2016-02-24 17:54
http://srv1.yogh.io/#json:getinfo
http://srv1.yogh.io/testnet/#json:getinfo

http://srv1.yogh.io/#addr:id:39XFme16GP2FMi2TCStZ2ciNNqe19jwDJb

Confirmed. Works fully. Thanks.

**Comment by unsystemizer** [comment] 2016-02-24 18:14
Pi is slow so it's going to take hours to build, but I'm past that point where I saw this error, so it's unlikely that this hasn't been fixed. I think you can close this.
Edit: built successfully.

**Closed as completed** 2016-02-24 19:21 UTC
Labels: bug
